/// An insight generated by the intelligence engine.
class Insight {
  final String id;
  final String title;
  final String description;
  final InsightType type;
  final DateTime generatedAt;

  const Insight({
    required this.id,
    required this.title,
    required this.description,
    required this.type,
    required this.generatedAt,
  });
}

enum InsightType {
  productivity,
  attendance,
  routine,
  burnout,
  streak,
  suggestion,
}
